-- =====================================================
-- ESQUEMA DUSAN — tablas originales (OBSOLETO 2026-04-22)
-- =====================================================
--
-- Este archivo quedo DEPRECADO tras la creacion de la skill
-- `protocolo-datos-unificado` (rama claude/unified-data-protocol-skill-yYQky).
--
-- Las 11 tablas `dusan_*` originales se eliminaron porque 6 duplicaban
-- tablas ya propuestas por la skill (tareas, decisiones_lock,
-- casos_asistente, contactos, plantillas_mensajes) y otras no aplicaban
-- como filas repetitivas (`dusan_contexto`).
--
-- Las 5 tablas que SI aportaban (objetivos, kpis, kpi_mediciones,
-- sesiones_trabajo, preguntas_abiertas) se reescribieron en formato skill
-- (snake_case plural, sin prefijo `dusan_`) y viven en:
--
--   esquema-dusan/tablas/tablas-skill-adicionales.sql
--
-- Fuente de verdad de TODO lo estructural: las tablas Supabase del
-- proyecto eknmtsrtfkzroxnovfqn. Consultar el catalogo en:
--
--   .claude/skills/protocolo-datos-unificado/TABLAS.md
--
-- SQL base de la skill (7 tablas) a correr PRIMERO:
--
--   .claude/skills/protocolo-datos-unificado/sql/20260422_tablas_base_protocolo.sql
--
-- SQL adicional (5 tablas de este esquema personal) a correr DESPUES:
--
--   esquema-dusan/tablas/tablas-skill-adicionales.sql
--
-- Ver tambien: esquema-dusan/ALINEACION-SKILL.md
-- =====================================================
